 
    # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GamesWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GamesWorld
 
    # keyboard toolbar
    pod 'IQKeyboardManagerSwift'
    # loading view like indicater
    pod 'MBProgressHUD'

end
